#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Read locale files
const enPath = path.join(__dirname, '../src/locales/en.json');
const dePath = path.join(__dirname, '../src/locales/de.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const de = JSON.parse(fs.readFileSync(dePath, 'utf8'));

// German translations for all remaining keys
// Using formal "Sie" form for UI, natural German pickleball terminology
const translations = {
  // leagueDetail section (144 keys)
  leagueDetail: {
    title: 'Liga-Details',
    overview: 'Überblick',
    standings: 'Tabelle',
    schedule: 'Spielplan',
    members: 'Mitglieder',
    rules: 'Regeln',
    chat: 'Chat',
    leagueInfo: 'Liga-Informationen',
    leagueName: 'Liga-Name',
    leagueType: 'Liga-Typ',
    season: 'Saison',
    status: 'Status',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    registrationDeadline: 'Anmeldefrist',
    maxParticipants: 'Max. Teilnehmer',
    currentParticipants: 'Aktuelle Teilnehmer',
    entryFee: 'Teilnahmegebühr',
    prizePool: 'Preispool',
    format: 'Format',
    matchFormat: 'Match-Format',
    scoringSystem: 'Wertungssystem',
    tiebreakRules: 'Tiebreak-Regeln',
    description: 'Beschreibung',
    organizer: 'Veranstalter',
    location: 'Ort',
    venue: 'Austragungsort',
    skillLevel: 'Spielstärke',
    minSkillLevel: 'Mind. Spielstärke',
    maxSkillLevel: 'Max. Spielstärke',
    registrationOpen: 'Anmeldung offen',
    registrationClosed: 'Anmeldung geschlossen',
    inProgress: 'Läuft',
    completed: 'Abgeschlossen',
    cancelled: 'Abgesagt',
    register: 'Anmelden',
    unregister: 'Abmelden',
    registered: 'Angemeldet',
    notRegistered: 'Nicht angemeldet',
    viewStandings: 'Tabelle ansehen',
    viewSchedule: 'Spielplan ansehen',
    viewMembers: 'Mitglieder ansehen',
    viewRules: 'Regeln ansehen',
    joinChat: 'Chat beitreten',
    leaveChat: 'Chat verlassen',
    shareLeague: 'Liga teilen',
    reportIssue: 'Problem melden',
    contactOrganizer: 'Veranstalter kontaktieren',
    rank: 'Rang',
    player: 'Spieler',
    wins: 'Siege',
    losses: 'Niederlagen',
    points: 'Punkte',
    matchesPlayed: 'Gespielte Matches',
    winPercentage: 'Siegquote',
    setsWon: 'Gewonnene Sätze',
    setsLost: 'Verlorene Sätze',
    gamesWon: 'Gewonnene Spiele',
    gamesLost: 'Verlorene Spiele',
    pointsFor: 'Punkte für',
    pointsAgainst: 'Punkte gegen',
    pointDifference: 'Punktdifferenz',
    form: 'Form',
    lastFiveMatches: 'Letzte 5 Matches',
    upcomingMatches: 'Anstehende Matches',
    completedMatches: 'Abgeschlossene Matches',
    round: 'Runde',
    date: 'Datum',
    time: 'Uhrzeit',
    court: 'Platz',
    player1: 'Spieler 1',
    player2: 'Spieler 2',
    score: 'Ergebnis',
    winner: 'Sieger',
    matchDetails: 'Match-Details',
    viewMatch: 'Match ansehen',
    reportScore: 'Ergebnis melden',
    confirmScore: 'Ergebnis bestätigen',
    disputeScore: 'Ergebnis anfechten',
    noUpcomingMatches: 'Keine anstehenden Matches',
    noCompletedMatches: 'Keine abgeschlossenen Matches',
    scheduleMatch: 'Match planen',
    rescheduleMatch: 'Match neu planen',
    cancelMatch: 'Match absagen',
    matchScheduled: 'Match geplant',
    matchRescheduled: 'Match neu geplant',
    matchCancelled: 'Match abgesagt',
    memberList: 'Mitgliederliste',
    memberCount: 'Mitgliederanzahl',
    viewProfile: 'Profil ansehen',
    sendMessage: 'Nachricht senden',
    challenge: 'Herausfordern',
    noMembers: 'Keine Mitglieder',
    rulesAndRegulations: 'Regeln und Vorschriften',
    generalRules: 'Allgemeine Regeln',
    scoringRules: 'Wertungsregeln',
    scheduleRules: 'Spielplanregeln',
    conductRules: 'Verhaltensregeln',
    penaltyRules: 'Strafregeln',
    disputeResolution: 'Streitbeilegung',
    noRules: 'Keine Regeln verfügbar',
    chatRoom: 'Chatraum',
    sendMessagePlaceholder: 'Nachricht eingeben...',
    send: 'Senden',
    noMessages: 'Noch keine Nachrichten',
    typing: 'tippt...',
    online: 'Online',
    offline: 'Offline',
    participants: 'Teilnehmer',
    leaveConfirm: 'Möchten Sie diese Liga wirklich verlassen?',
    leave: 'Verlassen',
    cancel: 'Abbrechen',
    joinConfirm: 'Möchten Sie dieser Liga beitreten?',
    join: 'Beitreten',
    paymentRequired: 'Zahlung erforderlich',
    proceedToPayment: 'Zur Zahlung',
    registrationSuccess: 'Erfolgreich angemeldet!',
    registrationError: 'Anmeldefehler',
    unregisterSuccess: 'Erfolgreich abgemeldet!',
    unregisterError: 'Abmeldefehler',
    loadingLeague: 'Liga wird geladen...',
    leagueNotFound: 'Liga nicht gefunden',
    errorLoadingLeague: 'Fehler beim Laden der Liga',
    refreshLeague: 'Liga aktualisieren',
    lastUpdated: 'Zuletzt aktualisiert',
    autoRefresh: 'Auto-Aktualisierung',
    notifications: 'Benachrichtigungen',
    enableNotifications: 'Benachrichtigungen aktivieren',
    disableNotifications: 'Benachrichtigungen deaktivieren',
    notificationSettings: 'Benachrichtigungseinstellungen',
    matchReminders: 'Match-Erinnerungen',
    scoreUpdates: 'Ergebnis-Updates',
    chatMessages: 'Chat-Nachrichten',
    leagueAnnouncements: 'Liga-Ankündigungen',
    standingsChanges: 'Tabellenänderungen',
    newMatches: 'Neue Matches',
    upcomingMatchReminder: 'Erinnerung: Anstehendes Match',
    matchIn24Hours: 'Sie haben ein Match in 24 Stunden',
    matchIn1Hour: 'Sie haben ein Match in 1 Stunde',
    scoreReported: 'Ergebnis gemeldet',
    scoreConfirmed: 'Ergebnis bestätigt',
    standingsUpdated: 'Tabelle aktualisiert',
  },

  // duesManagement section (139 keys)
  duesManagement: {
    title: 'Beitragsverwaltung',
    overview: 'Überblick',
    members: 'Mitglieder',
    payments: 'Zahlungen',
    settings: 'Einstellungen',
    totalDuesCollected: 'Gesammelte Beiträge gesamt',
    totalDuesOwed: 'Ausstehende Beiträge gesamt',
    paidMembers: 'Bezahlte Mitglieder',
    unpaidMembers: 'Unbezahlte Mitglieder',
    overdueDues: 'Überfällige Beiträge',
    upcomingDues: 'Anstehende Beiträge',
    collectionRate: 'Einzugsquote',
    averageDues: 'Durchschnittliche Beiträge',
    thisMonth: 'Dieser Monat',
    thisYear: 'Dieses Jahr',
    allTime: 'Gesamt',
    filterByStatus: 'Nach Status filtern',
    filterByPeriod: 'Nach Zeitraum filtern',
    searchMembers: 'Mitglieder suchen',
    memberName: 'Mitgliedsname',
    duesAmount: 'Beitragsbetrag',
    dueDate: 'Fälligkeitsdatum',
    status: 'Status',
    actions: 'Aktionen',
    paid: 'Bezahlt',
    unpaid: 'Unbezahlt',
    overdue: 'Überfällig',
    partial: 'Teilweise',
    exempted: 'Befreit',
    viewDetails: 'Details ansehen',
    recordPayment: 'Zahlung erfassen',
    sendReminder: 'Erinnerung senden',
    editDues: 'Beiträge bearbeiten',
    exemptMember: 'Mitglied befreien',
    paymentHistory: 'Zahlungshistorie',
    noMembers: 'Keine Mitglieder gefunden',
    noPayments: 'Keine Zahlungen',
    paymentDate: 'Zahlungsdatum',
    amount: 'Betrag',
    paymentMethod: 'Zahlungsmethode',
    reference: 'Referenz',
    notes: 'Notizen',
    recordedBy: 'Erfasst von',
    cash: 'Bar',
    card: 'Karte',
    bankTransfer: 'Banküberweisung',
    check: 'Scheck',
    online: 'Online',
    other: 'Sonstiges',
    recordPaymentTitle: 'Zahlung erfassen',
    paymentAmount: 'Zahlungsbetrag',
    selectPaymentMethod: 'Zahlungsmethode auswählen',
    paymentReference: 'Zahlungsreferenz',
    paymentNotes: 'Zahlungsnotizen',
    recordPaymentButton: 'Zahlung erfassen',
    cancel: 'Abbrechen',
    paymentRecorded: 'Zahlung erfasst',
    paymentError: 'Zahlungsfehler',
    sendReminderTitle: 'Erinnerung senden',
    reminderMessage: 'Erinnerungsnachricht',
    defaultReminderMessage: 'Freundliche Erinnerung: Ihr Vereinsbeitrag ist fällig.',
    sendReminderButton: 'Erinnerung senden',
    reminderSent: 'Erinnerung gesendet',
    reminderError: 'Fehler beim Senden der Erinnerung',
    bulkActions: 'Massenaktionen',
    selectAll: 'Alle auswählen',
    deselectAll: 'Auswahl aufheben',
    selected: 'Ausgewählt',
    sendReminders: 'Erinnerungen senden',
    exportData: 'Daten exportieren',
    duesSettingsTitle: 'Beitragseinstellungen',
    defaultDuesAmount: 'Standard-Beitragsbetrag',
    duesPeriod: 'Beitragszeitraum',
    monthly: 'Monatlich',
    quarterly: 'Vierteljährlich',
    yearly: 'Jährlich',
    oneTime: 'Einmalig',
    autoReminders: 'Auto-Erinnerungen',
    reminderFrequency: 'Erinnerungsfrequenz',
    reminderDaysBefore: 'Tage vor Fälligkeit',
    reminderDaysAfter: 'Tage nach Fälligkeit',
    gracePeriod: 'Kulanzfrist',
    gracePeriodDays: 'Kulanzfrist (Tage)',
    lateFee: 'Verspätungsgebühr',
    lateFeeAmount: 'Verspätungsgebührenbetrag',
    lateFeeType: 'Verspätungsgebührenart',
    flatFee: 'Pauschalgebühr',
    percentage: 'Prozentsatz',
    saveSettings: 'Einstellungen speichern',
    settingsSaved: 'Einstellungen gespeichert',
    settingsError: 'Fehler beim Speichern der Einstellungen',
    duesSchedule: 'Beitragsplan',
    scheduledDues: 'Geplante Beiträge',
    createSchedule: 'Plan erstellen',
    editSchedule: 'Plan bearbeiten',
    deleteSchedule: 'Plan löschen',
    scheduleTitle: 'Plan-Titel',
    scheduleDescription: 'Plan-Beschreibung',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    repeatInterval: 'Wiederholungsintervall',
    noRepeat: 'Keine Wiederholung',
    scheduleCreated: 'Plan erstellt',
    scheduleUpdated: 'Plan aktualisiert',
    scheduleDeleted: 'Plan gelöscht',
    scheduleError: 'Plan-Fehler',
    reports: 'Berichte',
    generateReport: 'Bericht erstellen',
    reportType: 'Berichtstyp',
    paymentSummary: 'Zahlungsübersicht',
    memberStatus: 'Mitgliederstatus',
    overdueReport: 'Überfälligkeitsbericht',
    collectionTrends: 'Einzugstrends',
    reportPeriod: 'Berichtszeitraum',
    generateButton: 'Erstellen',
    downloadReport: 'Bericht herunterladen',
    emailReport: 'Bericht per E-Mail senden',
    reportGenerated: 'Bericht erstellt',
    reportError: 'Berichtsfehler',
    exportFormat: 'Exportformat',
    csv: 'CSV',
    excel: 'Excel',
    pdf: 'PDF',
    exportSuccess: 'Export erfolgreich',
    exportError: 'Exportfehler',
    noData: 'Keine Daten verfügbar',
    loading: 'Lädt...',
    refresh: 'Aktualisieren',
    lastUpdated: 'Zuletzt aktualisiert',
  },

  // clubTournamentManagement section (131 keys)
  clubTournamentManagement: {
    title: 'Turnierverwaltung',
    createTournament: 'Turnier erstellen',
    editTournament: 'Turnier bearbeiten',
    deleteTournament: 'Turnier löschen',
    tournamentList: 'Turnierliste',
    upcomingTournaments: 'Anstehende Turniere',
    ongoingTournaments: 'Laufende Turniere',
    completedTournaments: 'Abgeschlossene Turniere',
    noTournaments: 'Keine Turniere',
    tournamentName: 'Turniername',
    tournamentType: 'Turniertyp',
    singleElimination: 'K.o.-System',
    doubleElimination: 'Doppel-K.o.-System',
    roundRobin: 'Jeder gegen jeden',
    swiss: 'Schweizer System',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    registrationDeadline: 'Anmeldefrist',
    maxParticipants: 'Max. Teilnehmer',
    currentParticipants: 'Aktuelle Teilnehmer',
    entryFee: 'Startgeld',
    prizePool: 'Preispool',
    firstPlace: '1. Platz',
    secondPlace: '2. Platz',
    thirdPlace: '3. Platz',
    tournamentFormat: 'Turnierformat',
    matchFormat: 'Match-Format',
    bestOf3: 'Best of 3',
    bestOf5: 'Best of 5',
    singleSet: 'Ein Satz',
    proSet: 'Pro-Set',
    scoringSystem: 'Wertungssystem',
    standard: 'Standard',
    noAd: 'No-Ad',
    tiebreak: 'Tiebreak',
    skillLevel: 'Spielstärke',
    openToAll: 'Offen für alle',
    beginnerOnly: 'Nur Anfänger',
    intermediateOnly: 'Nur Fortgeschrittene',
    advancedOnly: 'Nur Fortgeschrittene',
    description: 'Beschreibung',
    rules: 'Regeln',
    venue: 'Austragungsort',
    courts: 'Plätze',
    numberOfCourts: 'Anzahl Plätze',
    surface: 'Belag',
    indoor: 'Halle',
    outdoor: 'Freiplatz',
    organizer: 'Veranstalter',
    contactInfo: 'Kontaktinformation',
    status: 'Status',
    draft: 'Entwurf',
    open: 'Offen',
    registrationOpen: 'Anmeldung offen',
    registrationClosed: 'Anmeldung geschlossen',
    inProgress: 'Läuft',
    completed: 'Abgeschlossen',
    cancelled: 'Abgesagt',
    viewTournament: 'Turnier ansehen',
    registerForTournament: 'Für Turnier anmelden',
    unregisterFromTournament: 'Von Turnier abmelden',
    registered: 'Angemeldet',
    notRegistered: 'Nicht angemeldet',
    participants: 'Teilnehmer',
    participantList: 'Teilnehmerliste',
    viewParticipants: 'Teilnehmer ansehen',
    addParticipant: 'Teilnehmer hinzufügen',
    removeParticipant: 'Teilnehmer entfernen',
    seedParticipants: 'Teilnehmer setzen',
    drawBpaddle: 'Auslosung',
    bpaddle: 'Turnierplan',
    viewBpaddle: 'Turnierplan ansehen',
    updateBpaddle: 'Turnierplan aktualisieren',
    round: 'Runde',
    round1: 'Runde 1',
    round2: 'Runde 2',
    quarterfinals: 'Viertelfinale',
    semifinals: 'Halbfinale',
    final: 'Finale',
    thirdPlaceMatch: 'Spiel um Platz 3',
    match: 'Match',
    matches: 'Matches',
    matchNumber: 'Match-Nummer',
    court: 'Platz',
    date: 'Datum',
    time: 'Uhrzeit',
    player1: 'Spieler 1',
    player2: 'Spieler 2',
    score: 'Ergebnis',
    winner: 'Sieger',
    tbd: 'N.N.',
    bye: 'Freilos',
    scheduleMatch: 'Match planen',
    rescheduleMatch: 'Match neu planen',
    reportScore: 'Ergebnis melden',
    confirmScore: 'Ergebnis bestätigen',
    matchScheduled: 'Match geplant',
    scoreReported: 'Ergebnis gemeldet',
    scoreConfirmed: 'Ergebnis bestätigt',
    results: 'Ergebnisse',
    standings: 'Tabelle',
    viewResults: 'Ergebnisse ansehen',
    viewStandings: 'Tabelle ansehen',
    champion: 'Champion',
    runnerUp: 'Zweiter',
    thirdPlace: 'Dritter',
    statistics: 'Statistiken',
    totalMatches: 'Matches gesamt',
    completedMatches: 'Abgeschlossene Matches',
    upcomingMatches: 'Anstehende Matches',
    notifications: 'Benachrichtigungen',
    sendNotification: 'Benachrichtigung senden',
    notificationSent: 'Benachrichtigung gesendet',
    share: 'Teilen',
    shareTournament: 'Turnier teilen',
    export: 'Exportieren',
    exportBpaddle: 'Turnierplan exportieren',
    exportResults: 'Ergebnisse exportieren',
    print: 'Drucken',
    printBpaddle: 'Turnierplan drucken',
    settings: 'Einstellungen',
    tournamentSettings: 'Turniereinstellungen',
    saveSettings: 'Einstellungen speichern',
    createSuccess: 'Turnier erfolgreich erstellt',
    updateSuccess: 'Turnier erfolgreich aktualisiert',
    deleteSuccess: 'Turnier erfolgreich gelöscht',
    createError: 'Fehler beim Erstellen des Turniers',
    updateError: 'Fehler beim Aktualisieren des Turniers',
    deleteError: 'Fehler beim Löschen des Turniers',
    deleteConfirm: 'Möchten Sie dieses Turnier wirklich löschen?',
    confirm: 'Bestätigen',
    cancel: 'Abbrechen',
    loading: 'Lädt...',
    refresh: 'Aktualisieren',
  },

  // services section (110 keys) - Pickleball-specific service translations
  services: {
    auth: {
      signIn: 'Anmelden',
      signUp: 'Registrieren',
      signOut: 'Abmelden',
      forgotPassword: 'Passwort vergessen',
      resetPassword: 'Passwort zurücksetzen',
      changePassword: 'Passwort ändern',
      emailAddress: 'E-Mail-Adresse',
      password: 'Passwort',
      confirmPassword: 'Passwort bestätigen',
      rememberMe: 'Angemeldet bleiben',
      signInWithGoogle: 'Mit Google anmelden',
      signInWithApple: 'Mit Apple anmelden',
      signInWithFacebook: 'Mit Facebook anmelden',
      alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
      dontHaveAccount: 'Noch kein Konto?',
      termsAndConditions: 'AGB',
      privacyPolicy: 'Datenschutz',
      agreeToTerms: 'Ich stimme den AGB zu',
      signInSuccess: 'Erfolgreich angemeldet',
      signUpSuccess: 'Erfolgreich registriert',
      signOutSuccess: 'Erfolgreich abgemeldet',
      invalidCredentials: 'Ungültige Anmeldedaten',
      emailAlreadyExists: 'E-Mail bereits vorhanden',
      weakPassword: 'Passwort zu schwach',
      passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
      resetEmailSent: 'Passwort-Zurücksetzen-E-Mail gesendet',
      resetEmailError: 'Fehler beim Senden der E-Mail',
    },
    profile: {
      profile: 'Profil',
      editProfile: 'Profil bearbeiten',
      viewProfile: 'Profil ansehen',
      firstName: 'Vorname',
      lastName: 'Nachname',
      displayName: 'Anzeigename',
      bio: 'Über mich',
      dateOfBirth: 'Geburtsdatum',
      gender: 'Geschlecht',
      male: 'Männlich',
      female: 'Weiblich',
      other: 'Divers',
      preferNotToSay: 'Keine Angabe',
      location: 'Standort',
      city: 'Stadt',
      state: 'Bundesland',
      country: 'Land',
      phoneNumber: 'Telefonnummer',
      profilePicture: 'Profilbild',
      changePhoto: 'Foto ändern',
      removePhoto: 'Foto entfernen',
      uploadPhoto: 'Foto hochladen',
      saveChanges: 'Änderungen speichern',
      profileUpdated: 'Profil aktualisiert',
      profileUpdateError: 'Fehler beim Aktualisieren des Profils',
    },
    pickleball: {
      skillLevel: 'Spielstärke',
      playingStyle: 'Spielstil',
      dominantHand: 'Spielhand',
      rightHanded: 'Rechtshänder',
      leftHanded: 'Linkshänder',
      ambidextrous: 'Beidhändig',
      backhandStyle: 'Rückhand-Stil',
      oneHanded: 'Einhändig',
      twoHanded: 'Zweihändig',
      favoriteShot: 'Lieblingsschlag',
      forehand: 'Vorhand',
      backhand: 'Rückhand',
      serve: 'Aufschlag',
      volley: 'Volley',
      overhead: 'Überkopfschlag',
      preferredSurface: 'Bevorzugter Belag',
      hard: 'Hartplatz',
      clay: 'Sand',
      grass: 'Rasen',
      carpet: 'Teppich',
      yearsPlaying: 'Jahre Spielerfahrung',
      matchesPlayed: 'Gespielte Matches',
      matchesWon: 'Gewonnene Matches',
      winRate: 'Siegquote',
      currentRanking: 'Aktuelle Rangliste',
      highestRanking: 'Höchste Rangliste',
      achievements: 'Erfolge',
      tournamentWins: 'Turniersiege',
      favoritePlayer: 'Lieblingsspieler',
      availability: 'Verfügbarkeit',
      availableDays: 'Verfügbare Tage',
      preferredTimes: 'Bevorzugte Zeiten',
      morning: 'Morgen',
      afternoon: 'Nachmittag',
      evening: 'Abend',
    },
    matching: {
      findMatch: 'Match finden',
      createMatch: 'Match erstellen',
      joinMatch: 'Match beitreten',
      leaveMatch: 'Match verlassen',
      matchType: 'Match-Typ',
      singles: 'Einzel',
      doubles: 'Doppel',
      mixed: 'Mixed',
      skillLevelRange: 'Spielstärkebereich',
      anyLevel: 'Alle Stufen',
      location: 'Ort',
      searchRadius: 'Suchradius',
      dateTime: 'Datum & Uhrzeit',
      duration: 'Dauer',
      courtType: 'Platz-Typ',
      indoor: 'Halle',
      outdoor: 'Freiplatz',
      searchMatches: 'Matches suchen',
      noMatchesFound: 'Keine Matches gefunden',
      matchDetails: 'Match-Details',
      acceptMatch: 'Match annehmen',
      declineMatch: 'Match ablehnen',
      cancelMatch: 'Match absagen',
      matchAccepted: 'Match angenommen',
      matchDeclined: 'Match abgelehnt',
      matchCancelled: 'Match abgesagt',
      sendInvitation: 'Einladung senden',
      invitationSent: 'Einladung gesendet',
      invitationReceived: 'Einladung erhalten',
    },
  },

  // clubLeaguesTournaments section (80 keys)
  clubLeaguesTournaments: {
    title: 'Ligen & Turniere',
    leagues: 'Ligen',
    tournaments: 'Turniere',
    viewAll: 'Alle anzeigen',
    createLeague: 'Liga erstellen',
    createTournament: 'Turnier erstellen',
    upcoming: 'Anstehend',
    ongoing: 'Laufend',
    completed: 'Abgeschlossen',
    noLeagues: 'Keine Ligen',
    noTournaments: 'Keine Turniere',
    leagueName: 'Liga-Name',
    tournamentName: 'Turniername',
    season: 'Saison',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    participants: 'Teilnehmer',
    status: 'Status',
    viewDetails: 'Details ansehen',
    register: 'Anmelden',
    registered: 'Angemeldet',
    registrationOpen: 'Anmeldung offen',
    registrationClosed: 'Anmeldung geschlossen',
    registrationDeadline: 'Anmeldefrist',
    entryFee: 'Startgeld',
    prizePool: 'Preispool',
    format: 'Format',
    skillLevel: 'Spielstärke',
    division: 'Division',
    standings: 'Tabelle',
    schedule: 'Spielplan',
    results: 'Ergebnisse',
    bpaddle: 'Turnierplan',
    viewStandings: 'Tabelle ansehen',
    viewSchedule: 'Spielplan ansehen',
    viewResults: 'Ergebnisse ansehen',
    viewBpaddle: 'Turnierplan ansehen',
    rank: 'Rang',
    player: 'Spieler',
    team: 'Team',
    wins: 'Siege',
    losses: 'Niederlagen',
    draws: 'Unentschieden',
    points: 'Punkte',
    matchesPlayed: 'Gespielte Matches',
    round: 'Runde',
    date: 'Datum',
    time: 'Uhrzeit',
    court: 'Platz',
    score: 'Ergebnis',
    winner: 'Sieger',
    champion: 'Champion',
    runnerUp: 'Zweiter',
    semifinalists: 'Halbfinalisten',
    quarterfinalists: 'Viertelfinalisten',
    pastSeasons: 'Vergangene Saisons',
    currentSeason: 'Aktuelle Saison',
    nextSeason: 'Nächste Saison',
    joinLeague: 'Liga beitreten',
    leaveLeague: 'Liga verlassen',
    joinTournament: 'Turnier beitreten',
    leaveTournament: 'Turnier verlassen',
    leagueInfo: 'Liga-Informationen',
    tournamentInfo: 'Turnierinformationen',
    rules: 'Regeln',
    organizer: 'Veranstalter',
    contact: 'Kontakt',
    share: 'Teilen',
    loading: 'Lädt...',
    refresh: 'Aktualisieren',
    filter: 'Filter',
    filterBySkill: 'Nach Spielstärke filtern',
    filterByDivision: 'Nach Division filtern',
    filterByStatus: 'Nach Status filtern',
    search: 'Suchen',
    noResults: 'Keine Ergebnisse',
  },
};

// Deep merge function to preserve existing translations
function deepMerge(target, source) {
  const output = { ...target };

  for (const key in source) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      if (target[key] && typeof target[key] === 'object') {
        output[key] = deepMerge(target[key], source[key]);
      } else {
        output[key] = source[key];
      }
    } else {
      // Only update if the current value equals the English value (untranslated)
      // OR if the key doesn't exist
      if (!target[key] || target[key] === en[key]) {
        output[key] = source[key];
      } else {
        output[key] = target[key]; // Keep existing translation
      }
    }
  }

  return output;
}

// Count untranslated keys before
function countUntranslated(en, de, path = '') {
  let count = 0;

  for (const key in en) {
    const currentPath = path ? `${path}.${key}` : key;

    if (en[key] && typeof en[key] === 'object' && !Array.isArray(en[key])) {
      count += countUntranslated(en[key], de[key] || {}, currentPath);
    } else {
      // Check if this key is untranslated (same as English or missing)
      if (!de[key] || de[key] === en[key]) {
        count++;
      }
    }
  }

  return count;
}

console.log('\n🇩🇪 German Translation Script\n');
console.log('='.repeat(50));

const beforeCount = countUntranslated(en, de);
console.log(`\n📊 Untranslated keys before: ${beforeCount}`);

// Apply translations
const updated = deepMerge(de, translations);

const afterCount = countUntranslated(en, updated);
const translatedCount = beforeCount - afterCount;

console.log(`✅ Keys translated: ${translatedCount}`);
console.log(`📊 Remaining untranslated: ${afterCount}`);
console.log(`📈 Progress: ${((translatedCount / beforeCount) * 100).toFixed(1)}%`);

// Write updated file
fs.writeFileSync(dePath, JSON.stringify(updated, null, 2) + '\n', 'utf8');

console.log(`\n💾 Updated file: ${dePath}`);
console.log('='.repeat(50));
console.log('✨ Translation complete!\n');
